[package]
name = "prop_tune_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
prop_tune_core = {path = "../prop_tune_core"}
syn = { version = "*", features = ["extra-traits"] }
quote = "*"
proc-macro2 = "*"
